/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2023-03-23 00:48:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mall;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.ibatis.reflection.SystemMetaObject;
import com.ds.damin.mall.MallDto;
import java.util.List;

public final class p_005fwrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/mall/../include/css.jsp", Long.valueOf(1678191561032L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1674693996084L));
    _jspx_dependants.put("jar:file:/C:/webprograming/spring_workspace1/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LDM/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/mall/../include/nav.jsp", Long.valueOf(1679485540269L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.ibatis.reflection.SystemMetaObject");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.ds.damin.mall.MallDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("<title>insert_prodcut</title>\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write('\r');
      out.write('\n');

String ctx=request.getContextPath();
request.setAttribute("ctx", ctx);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("  <link href=\"https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=https://fonts.googleapis.com/css?family=Inconsolata:400,500,600,700|Raleway:400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/aos/aos.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/swiper/swiper-bundle.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("  \r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js\"></script>\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: MyPortfolio - v4.10.0\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/myportfolio-bootstrap-portfolio-website-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

	MallDto dto = (MallDto) request.getAttribute("MallDto");
	String mode = request.getParameter("mode");
	if(mode == null)
		mode="write";
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======= Navbar ======= -->\r\n");
      out.write("\t<div class=\"collapse navbar-collapse custom-navmenu\" id=\"main-navbar\">\r\n");
      out.write("\t\t<div class=\"container py-2 py-md-5\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-start justify-content-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"custom-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" onclick=\"category(1)\">신발</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\"  onclick=\"category(1)\">의류</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 d-none d-md-block  mr-auto\">\r\n");
      out.write("\t\t\t\t\t<div class=\"tweet d-flex\">\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<p>NEW BALANCE(뉴발란스)는 1906년 미국 매사추세츠 주 보스턴에서 발에 장애가 있거나 경찰 소방관 우체부 등 하루 종일 서서 일하는 발에 무리가 가는 사람들을 위해 아치 서포트(Arch Support : 지지대가 있는 신발 깔창)를\r\n");
      out.write("\t\t\t\t\t\t\t\t만드는데서부터 시작되었습니다. 닭의 세 개의 발톱이 만드는 균형 (Balance)에서 영감을 얻어 아치 서포트와 신발을 개발하였습니다. 지금의 뉴발란스(New balance)라는 회사명과 브랜드 명도 불균형한 발에 새로운 균형을 창조한다 하는 개념으로부터\r\n");
      out.write("\t\t\t\t\t\t\t\t유래되었습니다.</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2 \" style=\"text-align: right\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"custom-menu align-items-end\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/write\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-light custom-navbar\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mall/list\">NEW BALANCE</a> <a href=\"#\" class=\"burger\" data-bs-toggle=\"collapse\" data-bs-target=\"#main-navbar\">\r\n");
      out.write("\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<main id=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t\t<section class=\"section pb-5\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row mb-5 align-items-end\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\" data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t\t\t<h2>제품 등록</h2>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"mb-0\">제품 사진은 최대 3장, 빈 칸 없이 모두 기입 하시기 바랍니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<form name=\"myform\" id=\"myform\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"mode\" id=\"mode\" value=\"");
      out.print(mode);
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"p_seq\" id=\"p_seq\" value=\"");
      out.print(dto.getP_seq());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 mb-5 mb-md-0\" data-aos=\"fade-up\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row gy-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">제품명</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"p_name\" id=\"p_name\" value=\"");
      out.print(dto.getP_name());
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">가격</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"p_price\" class=\"form-control\" id=\"p_price\" value=\"");
      out.print(dto.getP_price());
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">사이즈</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"p_size\" id=\"p_size\" value=\"");
      out.print(dto.getP_size());
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-4 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">카테고리</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"p_category\" class=\"form-control\" id=\"p_category\" value=\"");
      out.print(dto.getP_category());
      out.write("\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">세부내용</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" name=\"p_contents\" cols=\"30\" rows=\"13\" required>");
      out.print(dto.getP_contents());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 mt-0 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"readmore d-block w-100\" name=\"btnSave\" id=\"btnSave\">저장하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 mb-5 mb-md-0\" data-aos=\"fade-up\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row gy-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");

								if (!mode.equals("update")) {
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">이미지1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"file1\" id=\"file1\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">이미지2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"file2\" id=\"file2\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"name\">이미지3</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"file3\" id=\"file3\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

									} else {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"name\">이미지1</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"file1\" id=\"file1\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"old_name\" id=\"old_name1\" value=\" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"name\">이미지2</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"file2\" id=\"file2\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"old_name\" id=\"old_name1\" value=\" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-12 form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label for=\"name\">이미지3</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"file\" class=\"form-control\" name=\"file3\" id=\"file3\" accept=\".jpg, .jpeg, .png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" name=\"old_name\" id=\"old_name1\" value=\" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");

										}
										
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</section>\r\n");
      out.write("\r\n");
      out.write("\t</main>\r\n");
      out.write("\t<!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- ======= Footer ======= -->\r\n");
      out.write("\t<footer class=\"footer\" role=\"contentinfo\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<p class=\"mb-1\">&copy; Copyright MyPortfolio. All Rights Reserved</p>\r\n");
      out.write("\t\t\t\t\t<div class=\"credits\">\r\n");
      out.write("\t\t\t\t\t\t<!--\r\n");
      out.write("            All the links in the footer should remain intact.\r\n");
      out.write("            You can delete the links only if you purchased the pro version.\r\n");
      out.write("            Licensing information: https://bootstrapmade.com/license/\r\n");
      out.write("            Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=MyPortfolio\r\n");
      out.write("          -->\r\n");
      out.write("\t\t\t\t\t\tDesigned by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a><br>\r\n");
      out.write("\t\t            \tModify by <a href=\"https://bootstrapmade.com/\">Damin</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6 social text-md-end\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><span class=\"bi bi-twitter\"></span></a> <a href=\"#\"><span class=\"bi bi-facebook\"></span></a> <a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"bi bi-instagram\"></span></a> <a href=\"#\"><span class=\"bi bi-linkedin\"></span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Vendor JS Files -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/aos/aos.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/isotope-layout/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Main JS File -->\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<script>\r\n");
      out.write("$(()=>{\r\n");
      out.write("\t$(\"#btnSave\").click(()=>{\r\n");
      out.write("\t\t//let data = $(\"#myform\").serialize();\r\n");
      out.write("\r\n");
      out.write("\t\tlet formData = new FormData( $(\"#myform\")[0] );\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlet url;\r\n");
      out.write("\t\tif($(\"#mode\").val()==\"update\")\r\n");
      out.write("\t\turl =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mall/update_save\";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\turl =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mall/save\";\r\n");
      out.write("\t\t//console.log(data);\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:url,\r\n");
      out.write("\t\t\tdata:formData,\r\n");
      out.write("\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t    processData:false,\r\n");
      out.write("\t\t    contentType:false,\r\n");
      out.write("\t\t\tenctype:\"multipart/form-data\",\r\n");
      out.write("\t\t\ttimeout:600000,\r\n");
      out.write("\t\t\ttype:\"POST\"\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t.done((res)=>{\r\n");
      out.write("\t\t\talert(res.res);\r\n");
      out.write("\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mall/list\";\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t.fail((res, status, error)=>{\r\n");
      out.write("\t\t\tconsole.log(error)\r\n");
      out.write("\t\t\tconsole.log(status)\r\n");
      out.write("\t\t\tconsole.log(res)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("// function setThumbnail(event) {\r\n");
      out.write("//         var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("//         reader.onload = function(event) {\r\n");
      out.write("//           var img = document.createElement(\"img\");\r\n");
      out.write("//           img.setAttribute(\"src\", event.target.result);\r\n");
      out.write("//           document.querySelector(\"div#image_container\").appendChild(img);\r\n");
      out.write("//         };\r\n");
      out.write("\r\n");
      out.write("//         reader.readAsDataURL(event.target.files[0]);\r\n");
      out.write("//       }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
